### ISSUE TITLE
Unable to cross compile ACE 7.0.2 (arm 32-bit)

### ISSUE THREAD

**Issue by JOO200** [DOCGroup/ACE_TAO#1514]
### Version

The version of ACE and/or TAO you are using
ACE 7.0.2

### Host machine and operating system
Debian amd64:
uname -a:
Linux <> 4.19.0-16-amd64 #1 SMP Debian 4.19.181-1 (2021-03-19) x86_64 GNU/Linux

### Target machine and operating system (if different from host)
Linux, gnu arm 32 bit

### Compiler name and version (including patch level)
```
root@host:~# g++ --version
g++ (Debian 8.3.0-6) 8.3.0
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

root@host:~# arm-linux-gnueabihf-g++ --version
arm-linux-gnueabihf-g++ (Debian 8.3.0-2) 8.3.0
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

### The $ACE_ROOT/ace/config.h file

The default implementation config_linux.h

### The $ACE_ROOT/include/makeinclude/platform_macros.GNU file

```
:~# cat ACE/include/makeinclude/platform_macros.GNU 
CROSS_COMPILE=arm-linux-gnueabihf-

ipv6=1
#xerces3=1
ssl=1

include $(ACE_ROOT)/include/makeinclude/platform_linux.GNU
```

### Contents of $ACE_ROOT/bin/MakeProjectCreator/config/default.features

```
ipv6=1
#xerces3=1
ssl=1
versioned_namespace=1
```

### AREA/CLASS/EXAMPLE AFFECTED:

I'm unable to compile the ACE core module.

### The problem effects:

Unable to link ACE with the arm-linux-gnueabihf-g++ compiler/linker.

### Synopsis

I'm unable to cross compile ACE for 32 bit arm.

### Description

I tried the update from 7.0.1 to 7.0.2. With 7.0.2 I'm unable to compile ACE as the linker is unable to link the shared objects.
```
/usr/lib/gcc-cross/arm-linux-gnueabihf/8/../../../../arm-linux-gnueabihf/bin/ld: .shobj/POSIX_Asynch_IO.o:(.rodata+0x2b4): multiple definition of `typeinfo name for ACE_Select_Reactor_T<ACE_Reactor_Token_T<ACE_Token> >'; .shobj/Asynch_Pseudo_Task.o:(.rodata+0x0): first defined here
/usr/lib/gcc-cross/arm-linux-gnueabihf/8/../../../../arm-linux-gnueabihf/bin/ld: .shobj/POSIX_Asynch_IO.o:(.data.rel.ro+0x7d0): multiple definition of `typeinfo for ACE_Select_Reactor_T<ACE_Reactor_Token_T<ACE_Token> >'; .shobj/Asynch_Pseudo_Task.o:(.data.rel.ro+0x0): first defined here
/usr/lib/gcc-cross/arm-linux-gnueabihf/8/../../../../arm-linux-gnueabihf/bin/ld: .shobj/POSIX_CB_Proactor.o:(.rodata+0x0): multiple definition of `typeinfo name for ACE_Select_Reactor_T<ACE_Reactor_Token_T<ACE_Token> >'; .shobj/Asynch_Pseudo_Task.o:(.rodata+0x0): first defined here
/usr/lib/gcc-cross/arm-linux-gnueabihf/8/../../../../arm-linux-gnueabihf/bin/ld: .shobj/POSIX_CB_Proactor.o:(.data.rel.ro+0x0): multiple definition of `typeinfo for ACE_Select_Reactor_T<ACE_Reactor_Token_T<ACE_Token> >'; .shobj/Asynch_Pseudo_Task.o:(.data.rel.ro+0x0): first defined here
/usr/lib/gcc-cross/arm-linux-gnueabihf/8/../../../../arm-linux-gnueabihf/bin/ld: .shobj/POSIX_Proactor.o:(.rodata+0x0): multiple definition of `typeinfo name for ACE_Select_Reactor_T<ACE_Reactor_Token_T<ACE_Token> >'; .shobj/Asynch_Pseudo_Task.o:(.rodata+0x0): first defined here
/usr/lib/gcc-cross/arm-linux-gnueabihf/8/../../../../arm-linux-gnueabihf/bin/ld: .shobj/POSIX_Proactor.o:(.data.rel.ro+0xbc): multiple definition of `typeinfo for ACE_Select_Reactor_T<ACE_Reactor_Token_T<ACE_Token> >'; .shobj/Asynch_Pseudo_Task.o:(.data.rel.ro+0x0): first defined here
/usr/lib/gcc-cross/arm-linux-gnueabihf/8/../../../../arm-linux-gnueabihf/bin/ld: .shobj/Priority_Reactor.o:(.rodata+0x0): multiple definition of `typeinfo name for ACE_Select_Reactor_T<ACE_Reactor_Token_T<ACE_Token> >'; .shobj/Asynch_Pseudo_Task.o:(.rodata+0x0): first defined here
/usr/lib/gcc-cross/arm-linux-gnueabihf/8/../../../../arm-linux-gnueabihf/bin/ld: .shobj/Priority_Reactor.o:(.data.rel.ro+0x0): multiple definition of `typeinfo for ACE_Select_Reactor_T<ACE_Reactor_Token_T<ACE_Token> >'; .shobj/Asynch_Pseudo_Task.o:(.data.rel.ro+0x0): first defined here
/usr/lib/gcc-cross/arm-linux-gnueabihf/8/../../../../arm-linux-gnueabihf/bin/ld: .shobj/Proactor.o:(.rodata+0x0): multiple definition of `typeinfo name for ACE_Select_Reactor_T<ACE_Reactor_Token_T<ACE_Token> >'; .shobj/Asynch_Pseudo_Task.o:(.rodata+0x0): first defined here
/usr/lib/gcc-cross/arm-linux-gnueabihf/8/../../../../arm-linux-gnueabihf/bin/ld: .shobj/Proactor.o:(.data.rel.ro+0x9c): multiple definition of `typeinfo for ACE_Select_Reactor_T<ACE_Reactor_Token_T<ACE_Token> >'; .shobj/Asynch_Pseudo_Task.o:(.data.rel.ro+0x0): first defined here
/usr/lib/gcc-cross/arm-linux-gnueabihf/8/../../../../arm-linux-gnueabihf/bin/ld: .shobj/Reactor.o:(.rodata+0x10): multiple definition of `typeinfo name for ACE_Select_Reactor_T<ACE_Reactor_Token_T<ACE_Token> >'; .shobj/Asynch_Pseudo_Task.o:(.rodata+0x0): first defined here
/usr/lib/gcc-cross/arm-linux-gnueabihf/8/../../../../arm-linux-gnueabihf/bin/ld: .shobj/Reactor.o:(.data.rel.ro+0xc): multiple definition of `typeinfo for ACE_Select_Reactor_T<ACE_Reactor_Token_T<ACE_Token> >'; .shobj/Asynch_Pseudo_Task.o:(.data.rel.ro+0x0): first defined here
/usr/lib/gcc-cross/arm-linux-gnueabihf/8/../../../../arm-linux-gnueabihf/bin/ld: .shobj/TP_Reactor.o:(.rodata+0x0): multiple definition of `typeinfo name for ACE_Select_Reactor_T<ACE_Reactor_Token_T<ACE_Token> >'; .shobj/Asynch_Pseudo_Task.o:(.rodata+0x0): first defined here
/usr/lib/gcc-cross/arm-linux-gnueabihf/8/../../../../arm-linux-gnueabihf/bin/ld: .shobj/TP_Reactor.o:(.data.rel.ro+0x0): multiple definition of `typeinfo for ACE_Select_Reactor_T<ACE_Reactor_Token_T<ACE_Token> >'; .shobj/Asynch_Pseudo_Task.o:(.data.rel.ro+0x0): first defined here
/usr/lib/gcc-cross/arm-linux-gnueabihf/8/../../../../arm-linux-gnueabihf/bin/ld: .shobj/FILE_Addr.o: in function `ACE_FILE_Addr::set(ACE_FILE_Addr const&)':
/home/host/cross/ACE_TAO/ACE/ace/OS_NS_stdlib.inl:285: Warnung:the use of `mktemp' is dangerous, better use `mkstemp' or `mkdtemp'
collect2: error: ld returned 1 exit status
make[1]: *** [/home/host/cross/ACE_TAO/ACE/include/makeinclude/rules.lib.GNU:245: libACE.so.7.0.2] Fehler 1
make[1]: Verzeichnis „/home/host/cross/ACE_TAO/ACE/ace“ wird verlassen
make: *** [GNUmakefile:262: ACE] Fehler 2
make: Verzeichnis „/home/host/cross/ACE_TAO/TAO“ wird verlassen
```

### Repeat by

I followed the Github workflow actions for linux ubuntu 18.04-g++8 and added the CROSS_COMPILE statement in the macros file. The command to build ACE_TAO returned with an error. The Linker is unable to create the shared objects.

### Sample fix/ workaround

Unknown

**Comment by jwillemsen** [comment]
There hasn't changed much between 7.0.1 and 7.0.2, did you do a build in a complete new tree with 7.0.2? Maybe check the compiler flags between 7.0.1 and 7.0.2 to see if something did change

**Comment by JOO200** [comment]
Yes, I checked out a clean version from git and removed all untracked and unversioned files.
I can compile (and link) the git tag `ACE+TAO-7_0_1`. I didn't changed any compiler flags and I'm unable to find changes in the git history.

**Comment by jwillemsen** [comment]
Can you add a snippet of compiling the ACE library itself with 7.0.1 and 7.0.2 to see if the compiler flags are the same?

**Comment by JOO200** [comment]
I uploaded the jenkins build log at
https://gist.github.com/JOO200/c55564bcea905031c1c53f7ac36c4484

The first different line is the linker line (7.0.2 instead of 7.0.1) and the error message.

**Comment by jwillemsen** [comment]
I have no idea why this would fail with 7.0.2, hard to tell without being to able to reproduce it here. I don't see that the settings you set in `default.features` do result in additional compiler flags to enable these features at compilation time, not sure if they are enabled in your build

**Comment by ischenk** [comment]
Isn't that issue caused by the removed check for _MSC_VER in above mentioned commit?
```
#if defined (_MSC_VER) && (_MSC_VER >= 1600)
   template class ACE_Export ACE_Select_Reactor_T<ACE_Select_Reactor_Token>;
#endif 
```
shouldn't that  be
```
#if defined (_MSC_VER)
   template class ACE_Export ACE_Select_Reactor_T<ACE_Select_Reactor_Token>;
#endif 
```
?

**Comment by jwillemsen** [comment]
Yes, the cleanup was not correct, instead of `_MSVC_VER` we should check `ACE_HAS_EXPLICIT_TEMPLATE_INSTANTIATION_EXPORT` which we do in other places in ACE. I have created #1515, can you try that fix also in your tree @JOO200?

**Comment by JOO200** [comment]
Yes, I can compile it with that change and your branch.

**Comment by jwillemsen** [comment]
Thanks for testing the change, when the CI checks are ok I will merge this with master and it will be part of the next ACE/TAO release

**Comment by jwillemsen** [comment]
In your build also `-fvisibility=hidden -fvisibility-inlines-hidden` is not part of the compiler flags, maybe that is something that is also related.
